### PR TITLE
Mac Fixes

### LINKED ISSUE #4: Overlapping layout of lyrics search results.
On MacOSX, a lyrics search yields the following window, whose size can not be altered. The lyrics are displayed on top of the search bar. The lyrics for `Buenos hermanos` by `Ibrahim Ferrer` were searched (and retrieved).

Thanks your work on the add-on. Let me know how I can help to fix this bug.

screen shot 2015-10-18 at 10 22 42

### PR DESCRIPTION
**Pull request by arolle**
fixes #4, introducing a modified layout:
screen shot 2015-10-22 at 17 58 12
Improving other mac specifics

### CODE REVIEW

**Comment by arolle** [comment]
fixed introduced issue with a52b125

**Comment by Smile4ever** [comment]
Thank you! I have one more fix to implement, after that I will increase the version number and release an EXE installer for Windows.

**Comment by Smile4ever** [comment]
The close button is missing here though, weird.

**Comment by Smile4ever** [comment]
Lol not so weird, it's just deactivated by a comment :)

**Pull request merged**
